before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d

language: go
services:
  - docker

script:
  - docker build -t verticalambition/etreservationapiserver .
  - echo "$DOCKER_PASSWORD" | docker login -u verticalambition --password-stdin
  - docker push verticalambition/etreservationapiserver:latest
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host 206.189.252.105\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh -i ./deploy_key root@206.189.252.105 pwd