language: go

before_install:
- ssh root@206.189.252.105 -p "SERVER_PASSWORD" pwd

#services:
#  - docker

#script:
#  - docker build -t verticalambition/etreservationapiserver .
#  - echo "$DOCKER_PASSWORD" | docker login -u verticalambition --password-stdin
#  - docker push verticalambition/etreservationapiserver:latest

