language: go
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
    -in deploy_key.enc -out ./deploy_key -d
  - echo "$DOCKER_PASSWORD" | docker login -u verticalambition --password-stdin
  - docker build -t verticalambition/etreservationapiserver .
  - docker push verticalambition/etreservationapiserver:latest
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host 161.35.250.136\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -o StrictHostKeyChecking=no -i ./deploy_key root@161.35.250.136 'docker pull verticalambition/etreservationapiserver:latest'
 # - ssh -o StrictHostKeyChecking=no -i ./deploy_key root@161.35.250.136 'docker run --name etapiserver -p 8080:8080 -d --rm verticalambition/etreservationapiserver'

#- docker pull verticalambition/etreservationapiserver:latest