language: go

before_install:
  - sudo apt-get install sshpass

script:
  - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@206.189.252.105 pwd

#services:
#  - docker

#script:
#  - docker build -t verticalambition/etreservationapiserver .
#  - echo "$DOCKER_PASSWORD" | docker login -u verticalambition --password-stdin
#  - docker push verticalambition/etreservationapiserver:latest

